export interface Platform {
  name: string;
  url: string;
  region: string;
  easySetup: "easy" | "medium" | "complex";
  connection: string;
  handoff: boolean;
  analytics: string;
  integrations: string;
  price: string;
  priceNum: number;
  notes: string;
  isLatam: boolean;
  userAnalysis: string[];
}

export const platforms: Platform[] = [
  {
    name: "Fastbots",
    url: "https://fastbots.ai",
    region: "USA",
    easySetup: "easy",
    connection: "WhatsApp, Messenger, IG, Telegram, Slack",
    handoff: true,
    analytics: "Medio",
    integrations: "Zapier, Make, WordPress, 8000+ apps",
    price: "$39",
    priceNum: 39,
    notes: "Business: 5 bots, 5K msgs, Multi-modelo, RAG completo",
    isLatam: false,
    userAnalysis: [
      "RAG Completo: Acepta archivos, URLs, texto plano y crawling de sitios web para entrenar al bot.",
      "Multi-Modelo: Permite elegir entre modelos de OpenAI, Anthropic y Google para cada bot.",
      "Multicanal Nativo: Integracion directa con WhatsApp, Messenger, Instagram, Telegram y Slack sin costos extra.",
      "No-Code Total: Configuracion muy sencilla, sin necesidad de conocimientos tecnicos. Setup en minutos.",
      "Zapier AI Actions: Los bots pueden ejecutar acciones en miles de apps durante la conversacion.",
      "Soporte Multilingue: Soporta ~95 idiomas con deteccion automatica.",
    ],
  },
  {
    name: "Builderbot",
    url: "https://builderbot.cloud",
    region: "LATAM / Global",
    easySetup: "easy",
    connection: "WhatsApp (QR + API Cloud)",
    handoff: true,
    analytics: "Basico",
    integrations: "CRM, Webhooks, API",
    price: "$40",
    priceNum: 40,
    notes: "No-code cloud, IA conversacional, transcribe audio",
    isLatam: true,
    userAnalysis: [
      "Open Source + Cloud: Tiene version open source (BuilderBot.app) para devs y version no-code cloud.",
      "IA Conversacional: Bot con IA integrada que interpreta, contextualiza y mantiene conversaciones naturales.",
      "Transcripcion de Audio: Capaz de entender mensajes de voz enviados por los clientes.",
      "Setup Rapido: Configuracion guiada, permite tener un bot funcionando en minutos sin programar.",
      "Comunidad Activa: Proyecto con comunidad de desarrolladores activa, ganador del primer premio en OpenExpo 2024.",
      "Orientado a LATAM: Documentacion y soporte en espanol, enfocado en el mercado latinoamericano.",
    ],
  },
  {
    name: "Manychat",
    url: "https://manychat.com",
    region: "USA",
    easySetup: "easy",
    connection: "WhatsApp, IG, Messenger",
    handoff: true,
    analytics: "Basico",
    integrations: "Zapier, Shopify, HubSpot",
    price: "$44",
    priceNum: 44,
    notes: "Con IA ($44/mes), AI Flow Builder",
    isLatam: false,
    userAnalysis: [
      "Sin RAG: El agente no utiliza bases de conocimiento externas, funciona mediante instrucciones configuradas en un esquema de nodos.",
      "Configuracion Amigable: El sistema de nodos conectados es muy intuitivo para el usuario.",
      "Integracion Directa: Conexion nativa con API Cloud y permiten coexistencia.",
      "Enfoque: Aunque ofrecen funciones de CRM, su gran fortaleza es la configuracion agil de bots automatizados.",
    ],
  },
  {
    name: "Botpress",
    url: "https://botpress.com",
    region: "Canada",
    easySetup: "medium",
    connection: "WABA oficial",
    handoff: true,
    analytics: "Avanzado",
    integrations: "Zapier, Make, webhooks",
    price: "$89",
    priceNum: 89,
    notes: "Plus: 2 bots, 5K msgs, Live Handoff",
    isLatam: false,
    userAnalysis: [
      "RAG Presente pero Limitado: Posee la funcion, pero en pruebas de campo la recuperacion de conocimiento mostro fallas.",
      "Visual & Potente: Disparadores drag & drop y esquema de redes de nodos muy visual.",
      "Capacidades Multimodales: Transcribe audio y genera imagenes nativamente.",
      "Complejidad Alta: Gran cantidad de elementos personalizables y parametros pueden abrumar.",
      "Enfoque: Full destinado a la generacion de bots complejos, no funciona como CRM.",
    ],
  },
  {
    name: "DanteAI",
    url: "https://dante-ai.com",
    region: "USA",
    easySetup: "easy",
    connection: "WhatsApp Integration",
    handoff: true,
    analytics: "Medio",
    integrations: "WhatsApp, Custom domains, API",
    price: "$99",
    priceNum: 99,
    notes: "10 bots, 50K responses, 10 seats",
    isLatam: false,
    userAnalysis: [
      "RAG Efectivo: Funciona correctamente, permitiendo modificar comportamiento e incluir links como fuente.",
      "UX Excelente: Interfaz muy pulida con configuracion via red de nodos super intuitiva.",
      "Setup Guiado: Cuenta con un asistente que guia la configuracion inicial paso a paso.",
      "Multiplataforma: Incluye WhatsApp y widgets web con facilidad.",
    ],
  },
  {
    name: "Laburen",
    url: "https://laburen.com",
    region: "Global",
    easySetup: "easy",
    connection: "WhatsApp",
    handoff: true,
    analytics: "Medio",
    integrations: "Integraciones premium",
    price: "$99",
    priceNum: 99,
    notes: "99 creditos/mes, sistema de creditos confuso",
    isLatam: false,
    userAnalysis: [
      "Asistente tipo GPT: Configuracion de bots muy facil guiada por chat, similar a crear un GPT personalizado.",
      "Sin RAG: No ofrece recuperacion de documentos.",
      "Acciones Integradas: Permite llamadas HTTP y compartir archivos desde la IA.",
      "Limitaciones: Muy facil de usar pero poco personalizable.",
      "Pricing Confuso: Sistema de cobro basado en 'creditos' opacos, dificil de calcular equivalencia en conversaciones reales.",
    ],
  },
  {
    name: "Cliengo",
    url: "https://www.cliengo.com",
    region: "Argentina",
    easySetup: "medium",
    connection: "API multicanal",
    handoff: true,
    analytics: "Medio",
    integrations: "Zapier, Google Ads, 1300+ apps",
    price: "$119",
    priceNum: 119,
    notes: "Fuerte en CRM, 3 agentes, 10 bots IA",
    isLatam: true,
    userAnalysis: [
      "Enfoque CRM: Su nucleo es la gestion de clientes, con un tablero tipo Kanban muy robusto.",
      "Estructura Rigida: Instrucciones y comportamiento poco personalizables (estilo modulos predefinidos).",
      "Sin RAG Documental: Solo se entrena escaneando el sitio web, no archivos PDF/Doc.",
      "Conexiones: Buenas integraciones via API y QR.",
    ],
  },
  {
    name: "YourGPT",
    url: "https://yourgpt.ai",
    region: "USA",
    easySetup: "easy",
    connection: "WABA oficial",
    handoff: true,
    analytics: "Medio",
    integrations: "Webhooks, API",
    price: "$129",
    priceNum: 129,
    notes: "5 bots, GPT-4, Developer oriented",
    isLatam: false,
    userAnalysis: [
      "RAG Avanzado: Soporta documentos, links y multiples fuentes de informacion.",
      "Developer First: Super configurable con multitud de parametros. Puede resultar complejo para usuarios no tecnicos.",
      "Copilot Studio: Estudio visual de nodos donde un Copilot puede crear flujos basados en prompts.",
      "Control Fino: Incluye configuracion de retraso en mensajes medido en milisegundos.",
    ],
  },
  {
    name: "Chatbase",
    url: "https://www.chatbase.co",
    region: "USA",
    easySetup: "easy",
    connection: "Cloud API oficial",
    handoff: false,
    analytics: "Medio",
    integrations: "Zapier, Make, n8n",
    price: "$150",
    priceNum: 150,
    notes: "Multi-modelo, Prompt unico",
    isLatam: false,
    userAnalysis: [
      "Bot Puro: Orientado 100% a la IA, no posee funciones de CRM.",
      "RAG Versatil: Acepta archivos, texto plano y sitios web.",
      "Prompting Modular: Las instrucciones se cargan en un solo bloque de texto.",
      "Multi-Modelo: Permite elegir y comparar entre diferentes modelos de IA (GPT, Claude, etc) en tiempo real.",
      "UI: Interfaz muy limpia y estetica.",
    ],
  },
  {
    name: "Chatfuel",
    url: "https://chatfuel.com",
    region: "USA",
    easySetup: "easy",
    connection: "BSP oficial Meta",
    handoff: true,
    analytics: "Medio",
    integrations: "Zapier, Sheets, Shopify",
    price: "$180",
    priceNum: 180,
    notes: "GPT-5.1, Buffering de mensajes",
    isLatam: false,
    userAnalysis: [
      "Sin RAG: No utiliza bases de conocimiento documentales.",
      "Personalizacion de Comportamiento: Gran control sobre longitud de respuesta y uso de emojis.",
      "Message Buffering: Posee 'retraso inteligente' para recopilar varios mensajes del usuario antes de responder.",
      "Multimedia: Capacidad para enviar imagenes.",
      "Instrucciones: Caja de texto unica, no modular.",
    ],
  },
  {
    name: "Landbot",
    url: "https://landbot.io",
    region: "Espana",
    easySetup: "easy",
    connection: "API oficial",
    handoff: true,
    analytics: "Avanzado",
    integrations: "Zapier, Make, Sheets, Slack",
    price: "$220",
    priceNum: 220,
    notes: "Visual builder, 3 seats, Testeo en vivo",
    isLatam: false,
    userAnalysis: [
      "RAG Hibrido: Funciona con links o archivos cargados.",
      "Data Persistence: Puede almacenar informacion generada durante la conversacion en variables.",
      "UI Elements: La IA es capaz de enviar botones, no solo texto.",
      "Prompting: Instrucciones en bloque unico con generador asistido por IA.",
      "Testing Innovador: Permite probar el bot enviando una interaccion real a tu WhatsApp personal.",
    ],
  },
  {
    name: "Tidio",
    url: "https://www.tidio.com",
    region: "Polonia",
    easySetup: "easy",
    connection: "WhatsApp + Multi-canal",
    handoff: true,
    analytics: "Medio",
    integrations: "Shopify, WordPress, Zapier",
    price: "$550",
    priceNum: 550,
    notes: "Lyro AI, Integracion E-commerce profunda",
    isLatam: false,
    userAnalysis: [
      "RAG & E-commerce: RAG via web/CSV/texto, pero destaca por integracion directa con listas de productos (Shopify/API).",
      "Comportamiento Configurable: Ajuste fino de tono, emojis, estilo de comunicacion y escalacion a humanos.",
      "Aprendizaje: Sistema de 'sugerencias' que permite a la IA aprender sobre la marcha.",
      "Hibrido: Posee bandeja de entrada (Inbox/CRM) pero con una orientacion muy fuerte a la automatizacion de bots.",
    ],
  },
];

export const topPlatforms = [
  {
    name: "Manychat",
    url: "https://manychat.com",
    tagline: "Mas accesible y facil de configurar",
    price: "$44",
    priceLabel: "/mes con IA",
    medal: "gold" as const,
  },
  {
    name: "Cliengo",
    url: "https://www.cliengo.com",
    tagline: "Mejor opcion para LATAM con espanol nativo",
    price: "$119",
    priceLabel: "/mes",
    medal: "silver" as const,
  },
  {
    name: "DanteAI",
    url: "https://dante-ai.com",
    tagline: "Mejor para escalar: multiples bots y clientes",
    price: "$99",
    priceLabel: "/mes",
    medal: "bronze" as const,
  },
];

export const boxplotPlatforms = [
  { name: "AIsensy Basic", price: 12 },
  { name: "AIsensy Pro", price: 29 },
  { name: "Fastbots", price: 39 },
  { name: "Builderbot", price: 40 },
  { name: "Manychat", price: 44 },
  { name: "Botpress", price: 89 },
  { name: "DanteAI", price: 99 },
  { name: "Laburen", price: 99 },
  { name: "Cliengo", price: 119 },
  { name: "YourGPT", price: 129 },
  { name: "Chatbase", price: 150 },
  { name: "Chatfuel", price: 180 },
  { name: "Landbot", price: 220 },
  { name: "Tidio", price: 550 },
];
